merge_fastq_pe:
  mem: "1G"
merge_fastq_se:
  mem: "1G"
sickle_pe:
  mem: "3G"
sickle_se:
  mem: "3G"
cutadapt_pe:
  mem: "3G"
cutadapt_se:
  mem: "3G"
fastqc_processed:
  mem: "10G"
fastqc_raw:
  mem: "10G"
md5:
  mem: "3G"
md5_check_raw:
  mem: "3G"
star:
  mem: "10G"
bam_index:
  mem: "3G"
htseq_fpg:
  mem: "3G"
htseq_fpe:
  mem: "3G"
merge_counts:
  mem: "10G"
