snakemake -p \
	--configfile $@ \
	--snakefile /exports/sasc/dcats/snakemake/RNAseq_multi_method/Snakefile \
	--cluster-config /exports/sasc/dcats/snakemake/RNAseq_multi_method/resources/cluster_config.yml \
	--latency-wait 90 \
	--drmaa " -N preprocessor -pe BWA {threads} -l h_vmem={cluster.mem} -q all.q -cwd -V" \
	--drmaa-log-dir $(pwd)/cluster_logs \
	--jobs 100 \
	--max-jobs-per-second 10 \
	--use-conda \
	--conda-prefix /exports/sasc/dcats/snakemake/.conda
